(prelude-require-packages
 '(project-explorer
   solarized-theme
   ein
   elpy
   monokai-theme
   tangotango-theme
   base16-theme
   emojify
   langtool
   define-word
   py-autopep8
   writegood-mode
   auctex-latexmk)
)
