(prelude-require-packages
 '(auctex-latexmk
   auto-complete-clang
   base16-theme
   blackboard-theme
   clang-format
   cmake-mode
   company-anaconda
   cpputils-cmake
   define-word
   ein
   elpy
   emojify
   helm-swoop
   langtool
   leuven-theme
   monokai-theme
   org-gnome
   org-pomodoro
   org-pomodoro
   org-projectile
   pdf-tools
   project-explorer
   py-autopep8
   rtags
   solarized-theme
   tangotango-theme
   writegood-mode)
 )
